# Generated by Django 4.2.6 on 2023-10-13 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_timestamp', models.DateTimeField(default=datetime.datetime(2023, 10, 13, 20, 49, 33, 214477, tzinfo=datetime.timezone.utc))),
                ('s3_url_raw', models.CharField(max_length=60)),
                ('s3_url_converted', models.CharField(max_length=60)),
            ],
        ),
    ]
