# Generated by Django 4.2.6 on 2023-10-14 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
