# Generated by Django 4.2.6 on 2023-10-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_upload_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='s3_url_converted',
        ),
        migrations.RemoveField(
            model_name='video',
            name='s3_url_raw',
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='s3_key',
            field=models.CharField(default='', max_length=36, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
