# Generated by Django 4.2.6 on 2023-10-18 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_remove_video_s3_url_converted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
