# Generated by Django 4.2.6 on 2023-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_video_s3_url_converted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='s3_key',
            field=models.CharField(default='', max_length=45, unique=True),
        ),
    ]
