# Generated by Django 4.2.6 on 2023-10-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_s3_key'),
        ('video', '0004_video_isprocessed_video_uploader_video_view'),
    ]

    operations = [
    ]
