# Generated by Django 4.2.6 on 2023-10-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_hasthumbnail_video_ischunked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='isProcessed',
            new_name='isConverted',
        ),
    ]
