# Generated by Django 4.2.6 on 2023-11-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_rename_isliked_like_is_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='is_liked',
            new_name='isLiked',
        ),
    ]
