# Generated by Django 4.2.6 on 2023-11-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_rename_is_liked_like_isliked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='isLiked',
            new_name='is_liked',
        ),
    ]
